---
title: "Degradome classification results unicellular and mature pollen"
output: 
  bookdown::html_document2:
    fig_caption : true
    self_contained: true
    toc: false
    toc_float: false
  <!-- pdf_document: default -->
# bibliography: Oliver-2022.bib
params:
  i.MF : 4
  i.conf : 0.95
  # working.dir: here("../../")
  output.dir: here("../../output/Report/")  
---
``` {r, include=FALSE, cache=FALSE,echo=TRUE}
knitr::read_chunk("05-Report.R")
```
```{r,setup,echo=FALSE}
## cat(getwd(),"\n")
```
# Summary of classification / filtering process
```{r,summary,echo=FALSE}

```
# WT vs miRNA775a-ox
### Classification results { - .tabset .tabset-pills}
#### General classification {-}
```{r,general-classification,echo=FALSE}

``` 
#### Classification 1 (Metrics) {-} 
```{r,classification1-metrics,echo=FALSE} 

``` 
#### Classification 2 (Coordinates) {-} 
```{r,classification2-coordinates,echo=FALSE} 

``` 
# Putative miRNA targets 
```{r,summary-miRtargets,echo=FALSE} 
``` 
# References 

